on: [push, pull_request]
#  push:
#    branches: [master]
name: Build Flatpak
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15
      options: --privileged
    steps:
    - uses: actions/checkout@v2

    # update the manifest to use HEAD rather than a git tag
    - name: Update manifest
      run: |
        pwd
        ls flatpak
        python3 scripts/flatpak-update.py
      shell: bash

    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
          manifest-path: flatpak/org.openchemistry.Avogadro2.yaml

    - name: Upload
      if: matrix.config.artifact != 0
      uses: actions/upload-artifact@v2
      with:
        path: *.flatpak
        name: Avogadro2.flatpak
